export const PLANT_LIB = [
    // Vegetables
    {
        name:"Tomato", category:"Vegetable",
        varieties:["Roma","Cherry","Beefsteak","San Marzano","Black Krim","Yellow Pear","Gardener's Delight","OG","OG-tomaat"],
        family:"Solanaceae", spacing_cm:60, row_spacing_cm:90, days_to_harvest:70, greenhouse:true,
        companions:["Basil","Marigold","Carrot","Parsley","Nasturtium","Borage","Chives","Calendula"],
        avoid:["Fennel","Broccoli","Cabbage","Cauliflower","Kale","Potato","Aubergine"],
        notes_growing:"Needs support. Pinch side shoots for indeterminate varieties. Water consistently to avoid blossom-end rot.",
    },
    {
        name:"Pepper", category:"Vegetable",
        varieties:["Sweet Bell","Paprika","Jalapeño","Cayenne","Cayennepeper","Habanero","Banana Pepper"],
        family:"Solanaceae", spacing_cm:45, row_spacing_cm:60, days_to_harvest:80, greenhouse:true,
        companions:["Basil","Marigold","Carrot","Tomato","Parsley"],
        avoid:["Fennel","Potato","Cabbage","Broccoli"],
        notes_growing:"Warm-season crop. Start indoors 8–10 weeks before last frost.",
    },
    {
        name:"Aubergine", category:"Vegetable",
        varieties:["Black Beauty","Listada di Gandia","White Egg","Slim Jim"],
        family:"Solanaceae", spacing_cm:60, row_spacing_cm:75, days_to_harvest:80, greenhouse:true,
        companions:["Basil","Marigold","Tarragon","Thyme"],
        avoid:["Fennel","Potato","Tomato"],
        notes_growing:"Needs long warm season. Benefits from greenhouse or polytunnel in cooler climates.",
    },
    {
        name:"Zucchini", category:"Vegetable",
        varieties:["Dark Green","Golden","Romanesco","Patio Star","Cocozelle"],
        family:"Cucurbitaceae", spacing_cm:90, row_spacing_cm:120, days_to_harvest:50,
        companions:["Nasturtium","Marigold","Dill","Borage","Sweetcorn","Pea"],
        avoid:["Potato","Fennel"],
        notes_growing:"Heavy feeder. Hand-pollinate early morning if fruit set is poor.",
    },
    {
        name:"Cucumber", category:"Vegetable",
        varieties:["Marketmore","Gherkin","Mini Munch","Straight Eight","Crystal Apple"],
        family:"Cucurbitaceae", spacing_cm:45, row_spacing_cm:90, days_to_harvest:55, greenhouse:true,
        companions:["Nasturtium","Marigold","Dill","Borage","Pea","Radish","Sunflower"],
        avoid:["Sage","Potato","Fennel","Basil"],
        notes_growing:"Needs warm soil. Train up a trellis to save space. Keep consistently moist.",
    },
    {
        name:"Pumpkin", category:"Vegetable",
        varieties:["Hokkaido","Butternut","Crown Prince","Atlantic Giant","Uchiki Kuri"],
        family:"Cucurbitaceae", spacing_cm:120, row_spacing_cm:180, days_to_harvest:100,
        companions:["Sweetcorn","Pea","Nasturtium","Marigold"],
        avoid:["Potato","Fennel"],
        notes_growing:"'Three Sisters' companion with corn and beans. Needs lots of space.",
    },
    {
        name:"Broccoli", category:"Vegetable",
        varieties:["Calabrese","Purple Sprouting","Romanesco","Tenderstem"],
        family:"Brassicaceae", spacing_cm:45, row_spacing_cm:60, days_to_harvest:80,
        companions:["Dill","Sage","Rosemary","Thyme","Marigold","Nasturtium","Celery","Beet"],
        avoid:["Tomato","Pepper","Strawberry","Fennel"],
        notes_growing:"Net against cabbage white butterfly. Use crop rotation to avoid clubroot.",
    },
    {
        name:"Cauliflower", category:"Vegetable",
        varieties:["Snowball","Violetta","Graffiti","All the Year Round"],
        family:"Brassicaceae", spacing_cm:50, row_spacing_cm:60, days_to_harvest:80,
        companions:["Dill","Sage","Rosemary","Thyme","Marigold","Celery"],
        avoid:["Tomato","Strawberry","Fennel"],
        notes_growing:"Blanch white varieties by tying leaves over the curd.",
    },
    {
        name:"Cabbage", category:"Vegetable",
        varieties:["January King","Savoy","Red Drumhead","Pointed","Hispi"],
        family:"Brassicaceae", spacing_cm:45, row_spacing_cm:60, days_to_harvest:90,
        companions:["Dill","Sage","Thyme","Rosemary","Marigold","Nasturtium","Celery"],
        avoid:["Tomato","Strawberry","Fennel","Garlic","Onion"],
        notes_growing:"Firm soil before planting to avoid loose heads. Net against pigeons.",
    },
    {
        name:"Kale", category:"Leafy Green",
        varieties:["Cavolo Nero","Curly Scotch","Red Russian","Dwarf Green Curled"],
        family:"Brassicaceae", spacing_cm:45, row_spacing_cm:60, days_to_harvest:60,
        companions:["Dill","Sage","Marigold","Nasturtium","Celery"],
        avoid:["Tomato","Strawberry","Fennel"],
        notes_growing:"Harvest outer leaves to extend season. Frost improves sweetness.",
    },
    {
        name:"Chard", category:"Leafy Green",
        varieties:["Rainbow","Bright Lights","White Silver","Rhubarb Chard","Fordhook Giant"],
        family:"Amaranthaceae", spacing_cm:30, row_spacing_cm:45, days_to_harvest:50,
        companions:["Lavender","Dill","Cabbage","Onion"],
        avoid:["Potato","Corn"],
        notes_growing:"Cut-and-come-again. Very cold tolerant. Sow successionally.",
    },
    {
        name:"Lettuce", category:"Leafy Green",
        varieties:["Butterhead","Cos","Little Gem","Oakleaf","Lollo Rosso","Batavia","Webb's Wonderful"],
        family:"Asteraceae", spacing_cm:25, row_spacing_cm:30, days_to_harvest:45,
        companions:["Carrot","Radish","Strawberry","Chives","Dill","Marigold","Nasturtium"],
        avoid:["Celery","Parsley","Fennel"],
        notes_growing:"Quick-maturing. Sow little and often every 2–3 weeks for continuous harvest.",
    },
    {
        name:"Spinach", category:"Leafy Green",
        varieties:["Baby Leaf","Monstrueux de Viroflay","Matador","Giant Noble"],
        family:"Amaranthaceae", spacing_cm:10, row_spacing_cm:30, days_to_harvest:40,
        companions:["Strawberry","Pea","Celery","Cauliflower","Radish"],
        avoid:["Fennel","Potato"],
        notes_growing:"Bolts in heat — sow spring and autumn. Prefers cool moist conditions.",
    },
    {
        name:"Rocket", category:"Leafy Green",
        varieties:["Wild","Cultivated","Sky Rocket","Wasabi"],
        family:"Brassicaceae", spacing_cm:15, row_spacing_cm:25, days_to_harvest:30,
        companions:["Lettuce","Radish","Spinach"],
        avoid:["Fennel"],
        notes_growing:"Cut-and-come-again. Bolts quickly in summer heat.",
    },
    {
        name:"Pak Choi", category:"Leafy Green",
        varieties:["Canton White","Joi Choi","Purple Rain","Mei Qing Choi"],
        family:"Brassicaceae", spacing_cm:20, row_spacing_cm:30, days_to_harvest:35,
        companions:["Dill","Marigold","Nasturtium"],
        avoid:["Tomato","Strawberry","Fennel"],
        notes_growing:"Fast-growing. Bolt-resistant varieties available. Net against flea beetle.",
    },
    {
        name:"Chicory", category:"Leafy Green",
        varieties:["Radicchio","Endive","Witloof","Puntarelle","Sugar Loaf"],
        family:"Asteraceae", spacing_cm:30, row_spacing_cm:35, days_to_harvest:90,
        companions:["Marigold","Calendula"],
        avoid:["Fennel"],
        notes_growing:"Blanch in autumn for milder flavour. Witloof forced in winter.",
    },
    {
        name:"Fennel", category:"Vegetable",
        varieties:["Florence","Romanesco","Zefa Fino","Perfection"],
        family:"Apiaceae", spacing_cm:30, row_spacing_cm:45, days_to_harvest:80,
        companions:["Dill"],
        avoid:["Tomato","Pepper","Courgette","Zucchini","Cucumber","Pumpkin","Bean","Pea","Carrot","Cabbage","Lettuce","Potato"],
        notes_growing:"Keep isolated — inhibits most other vegetables. Florence fennel needs mounding.",
    },
    {
        name:"Celery", category:"Vegetable",
        varieties:["Utah","Self-blanching","Giant Red","Tall Utah"],
        family:"Apiaceae", spacing_cm:25, row_spacing_cm:45, days_to_harvest:100,
        companions:["Cabbage","Tomato","Dill","Cosmos","Leek"],
        avoid:["Carrot","Parsley","Parsnip","Corn"],
        notes_growing:"Needs consistent moisture. Blanch stems by covering with soil or cardboard collars.",
    },
    {
        name:"Leek", category:"Vegetable",
        varieties:["Musselburgh","King Richard","Bleu de Solaise","Autumn Giant"],
        family:"Amaryllidaceae", spacing_cm:15, row_spacing_cm:30, days_to_harvest:100,
        companions:["Carrot","Celery","Onion","Parsley"],
        avoid:["Beans","Peas","Garlic"],
        notes_growing:"Transplant seedlings into deep holes. Earth up for longer white stems.",
    },
    {
        name:"Onion", category:"Vegetable",
        varieties:["Red Baron","Stuttgart","Sturon","White Lisbon","Spring Onion","Lente ui","Ailsa Craig"],
        family:"Amaryllidaceae", spacing_cm:10, row_spacing_cm:25, days_to_harvest:100,
        companions:["Carrot","Beetroot","Lettuce","Chamomile","Parsnip","Tomato"],
        avoid:["Beans","Peas","Sage","Asparagus"],
        notes_growing:"Onion fly deterred by carrot companion. Harvest when foliage falls over.",
    },
    {
        name:"Garlic", category:"Vegetable",
        varieties:["Softneck","Hardneck","Elephant","Solent Wight","Lautrec Wight"],
        family:"Amaryllidaceae", spacing_cm:15, row_spacing_cm:30, days_to_harvest:240,
        companions:["Tomato","Rose","Carrot","Celery","Beetroot","Lettuce"],
        avoid:["Beans","Peas","Asparagus","Sage"],
        notes_growing:"Plant cloves in autumn for best yield. Harvest when leaves turn yellow.",
    },
    {
        name:"Shallot", category:"Vegetable",
        varieties:["Zebrune","Ambition","Red Sun","Mikor"],
        family:"Amaryllidaceae", spacing_cm:15, row_spacing_cm:25, days_to_harvest:90,
        companions:["Carrot","Tomato","Beetroot"],
        avoid:["Beans","Peas","Asparagus"],
        notes_growing:"Plant sets in spring or autumn. Each set produces a cluster of bulbs.",
    },
    {
        name:"Sweetcorn", category:"Vegetable",
        varieties:["Earlibird","Golden Bantam","Painted Mountain","Swift","Lark"],
        family:"Poaceae", spacing_cm:35, row_spacing_cm:45, days_to_harvest:80,
        companions:["Pumpkin","Zucchini","Pea","French Bean","Nasturtium","Sunflower"],
        avoid:["Tomato","Celery"],
        notes_growing:"Plant in blocks (not rows) for good pollination. 'Three Sisters' companion with squash and beans.",
    },
    {
        name:"Artichoke", category:"Vegetable",
        varieties:["Green Globe","Violetto","Romanesco","Gros Vert de Laon"],
        family:"Asteraceae", spacing_cm:90, row_spacing_cm:120, days_to_harvest:365,
        companions:["Sunflower","Tarragon"],
        avoid:["Potato"],
        notes_growing:"Perennial. Cut back to ground in autumn. Mulch well. Productive for 5+ years.",
    },
    {
        name:"Asparagus", category:"Vegetable",
        varieties:["Jersey Knight","Gijnlim","Connover's Colossal","Pacific Purple"],
        family:"Asparagaceae", spacing_cm:45, row_spacing_cm:120, days_to_harvest:730,
        companions:["Tomato","Parsley","Basil","Marigold"],
        avoid:["Onion","Garlic","Potato","Fennel"],
        notes_growing:"Perennial. Do not harvest in year 1–2. Leave ferny growth to feed crown.",
    },
    {
        name:"Courgette", category:"Vegetable",
        varieties:["Atena","Venus","Defender","Black Forest"],
        family:"Cucurbitaceae", spacing_cm:90, row_spacing_cm:120, days_to_harvest:50,
        companions:["Nasturtium","Marigold","Borage","Pea"],
        avoid:["Potato","Fennel"],
        notes_growing:"Harvest regularly when small to keep plants productive.",
    },
    {
        name:"Peas (Sugar)", category:"Legume",
        varieties:["Oregon Sugar Pod","Carouby de Maussane","Golden Sweet","Shiraz"],
        family:"Fabaceae", spacing_cm:10, row_spacing_cm:45, days_to_harvest:60,
        companions:["Carrot","Radish","Spinach","Lettuce","Cucumber","Mint","Turnip"],
        avoid:["Onion","Garlic","Shallot","Leek","Fennel"],
        notes_growing:"Needs support. Fixes nitrogen. Do not over-fertilise.",
    },
    // Roots
    {
        name:"Carrot", category:"Root",
        varieties:["Nantes","Chantenay","Paris Market","Cosmic Purple","White Satin","Autumn King"],
        family:"Apiaceae", spacing_cm:8, row_spacing_cm:30, days_to_harvest:70,
        companions:["Leek","Onion","Chives","Rosemary","Sage","Lettuce","Tomato","Radish"],
        avoid:["Dill","Celery","Parsnip","Potato","Fennel"],
        notes_growing:"Sow direct — dislikes transplanting. Thin to avoid forking. Carrot fly deterred by onion family.",
    },
    {
        name:"Beetroot", category:"Root",
        varieties:["Boltardy","Chioggia","Golden","Cylindra","Bull's Blood","Action"],
        family:"Amaranthaceae", spacing_cm:10, row_spacing_cm:30, days_to_harvest:60,
        companions:["Onion","Lettuce","Kohlrabi","Garlic","Mint","Catnip"],
        avoid:["Runner Bean","Tall spinach","Mustard","Pole Bean"],
        notes_growing:"Sow direct or transplant carefully. Harvest young for salads.",
    },
    {
        name:"Parsnip", category:"Root",
        varieties:["Gladiator","Tender & True","Hollow Crown","White Gem"],
        family:"Apiaceae", spacing_cm:15, row_spacing_cm:30, days_to_harvest:120,
        companions:["Pea","Garlic","Rosemary","Peppers"],
        avoid:["Carrot","Celery","Dill","Fennel"],
        notes_growing:"Slow to germinate. Use fresh seed each year. Frost improves sweetness.",
    },
    {
        name:"Turnip", category:"Root",
        varieties:["Purple Top","Tokyo Cross","Milan White","Golden Ball"],
        family:"Brassicaceae", spacing_cm:15, row_spacing_cm:30, days_to_harvest:50,
        companions:["Pea","Nasturtium","Hairy Vetch"],
        avoid:["Potato","Fennel","Hedge Mustard"],
        notes_growing:"Harvest young (tennis-ball size). Leaves are edible.",
    },
    {
        name:"Radish", category:"Root",
        varieties:["French Breakfast","Cherry Belle","Watermelon","Daikon","Black Spanish"],
        family:"Brassicaceae", spacing_cm:5, row_spacing_cm:20, days_to_harvest:25,
        companions:["Lettuce","Carrot","Cucumber","Pea","Spinach","Nasturtium"],
        avoid:["Hyssop","Agastache"],
        notes_growing:"Fastest vegetable to mature. Sow successionally every 2 weeks. Great for marking rows.",
    },
    {
        name:"Potato", category:"Root",
        varieties:["Charlotte","Maris Piper","King Edward","Desiree","Pink Fir Apple","Jersey Royal"],
        family:"Solanaceae", spacing_cm:30, row_spacing_cm:75, days_to_harvest:100,
        companions:["Marigold","Nasturtium","Horseradish","Thyme","Chamomile","Yarrow"],
        avoid:["Tomato","Aubergine","Pepper","Cucumber","Sunflower","Pumpkin","Fennel"],
        notes_growing:"Earth up as shoots emerge. Chit earlies 6 weeks before planting.",
    },
    {
        name:"Sweet Potato", category:"Root",
        varieties:["Beauregard","Hernandez","O'Henry","Erato Orange"],
        family:"Convolvulaceae", spacing_cm:30, row_spacing_cm:75, days_to_harvest:100, greenhouse:true,
        companions:["Nasturtium","Dill","Thyme"],
        avoid:["Sunflower","Squash"],
        notes_growing:"Needs warm soil (18°C+). Plant slips after last frost.",
    },
    {
        name:"Celeriac", category:"Root",
        varieties:["Prinz","Giant Prague","Monarch","Brilliant"],
        family:"Apiaceae", spacing_cm:30, row_spacing_cm:45, days_to_harvest:180,
        companions:["Leek","Onion","Beans"],
        avoid:["Carrot","Parsley","Fennel"],
        notes_growing:"Long season. Start indoors in February. Remove outer leaves in autumn.",
    },
    {
        name:"Swede", category:"Root",
        varieties:["Marian","Best of All","Wilhemsburger"],
        family:"Brassicaceae", spacing_cm:20, row_spacing_cm:35, days_to_harvest:90,
        companions:["Nasturtium","Pea"],
        avoid:["Fennel","Potato"],
        notes_growing:"Sow in late spring. Frost-hardy. Leave in ground and harvest as needed.",
    },
    // Herbs
    {
        name:"Basil", category:"Herb",
        varieties:["Genovese","Thai","Purple Opal","Lemon","Holy","Greek Miniature","Basilicum"],
        family:"Lamiaceae", spacing_cm:20, row_spacing_cm:30, days_to_harvest:30, greenhouse:true,
        companions:["Tomato","Pepper","Marigold","Oregano"],
        avoid:["Sage","Cucumber","Fennel"],
        notes_growing:"Pinch flower buds to extend leaf production. Dislikes cold; grow under cover in cool climates.",
    },
    {
        name:"Parsley", category:"Herb",
        varieties:["Flat-leaf","Curly","Krul peterselie","Hamburg Root","Italian Giant"],
        family:"Apiaceae", spacing_cm:20, row_spacing_cm:30, days_to_harvest:70,
        companions:["Asparagus","Tomato","Chives","Carrot","Rose"],
        avoid:["Lettuce","Onion","Fennel","Mint"],
        notes_growing:"Slow to germinate. Biennial — leaves in year 1, flowers in year 2. Self-seeds readily.",
    },
    {
        name:"Cilantro", category:"Herb",
        varieties:["Leisure","Confetti","Santo","Calypso"],
        family:"Apiaceae", spacing_cm:10, row_spacing_cm:25, days_to_harvest:30,
        companions:["Spinach","Basil","Parsley"],
        avoid:["Fennel","Dill"],
        notes_growing:"Sow direct every few weeks. Bolts in heat — use slow-bolt varieties in summer.",
    },
    {
        name:"Dill", category:"Herb",
        varieties:["Bouquet","Fernleaf","Mammoth","Dukat"],
        family:"Apiaceae", spacing_cm:15, row_spacing_cm:30, days_to_harvest:40,
        companions:["Cucumber","Lettuce","Cabbage","Broccoli","Onion"],
        avoid:["Carrot","Fennel","Tomato","Celery"],
        notes_growing:"Sow direct. Dill near carrot crosses and weakens both. Keep apart from fennel.",
    },
    {
        name:"Chives", category:"Herb",
        varieties:["Common","Garlic Chives","Giant Siberian","Staro"],
        family:"Amaryllidaceae", spacing_cm:20, row_spacing_cm:25, days_to_harvest:60,
        companions:["Carrot","Tomato","Rose","Parsley","Brassicas"],
        avoid:["Beans","Peas","Asparagus"],
        notes_growing:"Perennial. Cut back hard after flowering to encourage fresh growth.",
    },
    {
        name:"Mint", category:"Herb",
        varieties:["Spearmint","Peppermint","Apple Mint","Chocolate Mint","Moroccan","Munt"],
        family:"Lamiaceae", spacing_cm:30, row_spacing_cm:40, days_to_harvest:30,
        companions:["Brassicas","Tomato","Pea"],
        avoid:["Parsley","Chamomile"],
        notes_growing:"Invasive — grow in a buried pot. Deters aphids, flea beetles, and ants.",
    },
    {
        name:"Oregano", category:"Herb",
        varieties:["Greek","Italian","Golden","Compactum"],
        family:"Lamiaceae", spacing_cm:30, row_spacing_cm:40, days_to_harvest:60,
        companions:["Tomato","Pepper","Broccoli","Cucumber"],
        avoid:["Fennel"],
        notes_growing:"Perennial. Harvest just before flowering for best flavour.",
    },
    {
        name:"Thyme", category:"Herb",
        varieties:["Common","Lemon","Silver Posie","Creeping","Doone Valley"],
        family:"Lamiaceae", spacing_cm:30, row_spacing_cm:40, days_to_harvest:60,
        companions:["Brassicas","Tomato","Potato","Strawberry","Rose"],
        avoid:["Fennel"],
        notes_growing:"Perennial. Drought-tolerant once established. Deters cabbage worm and aphids.",
    },
    {
        name:"Rosemary", category:"Herb",
        varieties:["Tuscan Blue","Miss Jessopp","Majorca Pink","Prostratus"],
        family:"Lamiaceae", spacing_cm:60, row_spacing_cm:60, days_to_harvest:60,
        companions:["Brassicas","Carrot","Sage","Thyme","Beans"],
        avoid:["Potato","Pumpkin","Fennel"],
        notes_growing:"Perennial shrub. Frost-hardy once established. Good near Brassicas — repels cabbage fly.",
    },
    {
        name:"Sage", category:"Herb",
        varieties:["Common","Purple","Tricolor","Pineapple","Icterina"],
        family:"Lamiaceae", spacing_cm:45, row_spacing_cm:60, days_to_harvest:60,
        companions:["Brassicas","Carrot","Tomato","Rosemary","Strawberry"],
        avoid:["Cucumber","Basil","Onion"],
        notes_growing:"Perennial. Prune after flowering to prevent woodiness. Repels cabbage moth.",
    },
    {
        name:"Tarragon", category:"Herb",
        varieties:["French","Russian","Mexican"],
        family:"Asteraceae", spacing_cm:45, row_spacing_cm:60, days_to_harvest:60,
        companions:["Aubergine","Pepper","Salad Greens"],
        avoid:["Fennel"],
        notes_growing:"French tarragon is superior. Cannot be grown from seed (use cuttings/division).",
    },
    {
        name:"Lemon Balm", category:"Herb",
        varieties:["Common","Variegated","Aurea","Quedlinburger"],
        family:"Lamiaceae", spacing_cm:45, row_spacing_cm:60, days_to_harvest:60,
        companions:["Tomato","Squash","Pumpkin"],
        avoid:["Fennel"],
        notes_growing:"Perennial. Can be invasive — deadhead before seeds set. Attracts pollinators.",
    },
    {
        name:"Lavender", category:"Herb",
        varieties:["Hidcote","Munstead","Vera","Grosso","Phenomenal"],
        family:"Lamiaceae", spacing_cm:45, row_spacing_cm:60, days_to_harvest:90,
        companions:["Brassicas","Tomato","Rose","Oregano"],
        avoid:["Fennel"],
        notes_growing:"Perennial. Prune after flowering — never cut into old wood. Excellent pollinator plant.",
    },
    {
        name:"Borage", category:"Herb",
        varieties:["Common","White Flowered","Creeping"],
        family:"Boraginaceae", spacing_cm:30, row_spacing_cm:45, days_to_harvest:45,
        companions:["Tomato","Squash","Strawberry","Cucumber"],
        avoid:["Fennel"],
        notes_growing:"Self-seeds freely. Edible flowers attract bees. Deters tomato hornworm.",
    },
    {
        name:"Chervil", category:"Herb",
        varieties:["Common","Curled","Brussels Winter"],
        family:"Apiaceae", spacing_cm:10, row_spacing_cm:25, days_to_harvest:30,
        companions:["Radish","Lettuce","Brassicas"],
        avoid:["Fennel","Carrot"],
        notes_growing:"Prefers light shade. Bolts in heat. Great for spring and autumn.",
    },
    {
        name:"Lovage", category:"Herb",
        varieties:["Common"],
        family:"Apiaceae", spacing_cm:60, row_spacing_cm:90, days_to_harvest:60,
        companions:["Beans","Brassicas"],
        avoid:["Fennel"],
        notes_growing:"Perennial — very tall (2m+). Celery-like flavour. Attracts beneficial insects.",
    },
    {
        name:"Marjoram", category:"Herb",
        varieties:["Sweet","Pot","Golden","Compact"],
        family:"Lamiaceae", spacing_cm:30, row_spacing_cm:40, days_to_harvest:60,
        companions:["Tomato","Pepper","Cucumber","Onion","Basil"],
        avoid:["Fennel"],
        notes_growing:"Similar to oregano. Sweet marjoram is tender — treat as annual in cool climates.",
    },
    // Legumes
    {
        name:"French Bean", category:"Legume",
        varieties:["Blue Lake","Cobra","Borlotti","Dwarf Tendergreen","Climbing Neckarqueen"],
        family:"Fabaceae", spacing_cm:15, row_spacing_cm:45, days_to_harvest:60,
        companions:["Carrot","Cucumber","Strawberry","Celery","Summer Savory","Beetroot","Radish"],
        avoid:["Fennel","Onion","Garlic","Shallot","Leek","Sunflower"],
        notes_growing:"Fixes nitrogen. Do not over-fertilise. Climbing types need 2m+ support.",
    },
    {
        name:"Runner Bean", category:"Legume",
        varieties:["Scarlet Emperor","Enorma","White Lady","Painted Lady","Hestia"],
        family:"Fabaceae", spacing_cm:20, row_spacing_cm:60, days_to_harvest:60,
        companions:["Carrot","Radish","Cucumber","Sweetcorn","Summer Savory"],
        avoid:["Fennel","Onion","Garlic","Beet","Cabbage","Sunflower"],
        notes_growing:"Needs 2.5m support. Mist flowers to aid fruit set in dry weather.",
    },
    {
        name:"Broad Bean", category:"Legume",
        varieties:["Aquadulce Claudia","The Sutton","Witkiem Manita","Imperial Green Longpod"],
        family:"Fabaceae", spacing_cm:20, row_spacing_cm:45, days_to_harvest:90,
        companions:["Carrot","Potato","Parsley","Summer Savory","Spinach"],
        avoid:["Fennel","Onion","Garlic"],
        notes_growing:"Autumn-sow for early crop. Pinch out growing tips when first pods form to deter blackfly.",
    },
    {
        name:"Pea", category:"Legume",
        varieties:["Kelvedon Wonder","Sugar Snap","Mangetout","Petit Pois","Telephone"],
        family:"Fabaceae", spacing_cm:8, row_spacing_cm:45, days_to_harvest:60,
        companions:["Carrot","Radish","Lettuce","Spinach","Cucumber","Turnip","Mint"],
        avoid:["Onion","Garlic","Shallot","Leek","Fennel"],
        notes_growing:"Needs support. Fixes nitrogen. Sow direct — dislikes transplanting.",
    },
    {
        name:"Borlotti Bean", category:"Legume",
        varieties:["Lingua di Fuoco","Lamon","Yin Yang"],
        family:"Fabaceae", spacing_cm:15, row_spacing_cm:45, days_to_harvest:80,
        companions:["Carrot","Cucumber","Celery"],
        avoid:["Fennel","Onion","Garlic"],
        notes_growing:"Dry or fresh. Leave pods on plant until papery for dried beans.",
    },
    // Fruits
    {
        name:"Strawberry", category:"Fruit",
        varieties:["Elsanta","Mara des Bois","Honeoye","Aromel","Cambridge Favourite"],
        family:"Rosaceae", spacing_cm:30, row_spacing_cm:75, days_to_harvest:365,
        companions:["Borage","Thyme","Sage","Spinach","Lettuce","Carrot","Marigold"],
        avoid:["Broccoli","Cabbage","Cauliflower","Fennel","Potato","Tomato"],
        notes_growing:"Perennial. Replace every 3–4 years. Net against birds. Propagate via runners.",
    },
    {
        name:"Raspberry", category:"Fruit",
        varieties:["Glen Ample","Autumn Bliss","Joan J","Tulameen","Polka"],
        family:"Rosaceae", spacing_cm:45, row_spacing_cm:180, days_to_harvest:365,
        companions:["Marigold","Garlic","Nasturtium","Tansy"],
        avoid:["Potato","Tomato","Strawberry (same bed)","Fennel"],
        notes_growing:"Summer-fruiting: prune floricanes after harvest. Autumn-fruiting: cut all canes to ground in February.",
    },
    {
        name:"Blueberry", category:"Fruit",
        varieties:["Bluecrop","Duke","Chandler","Pink Lemonade","Patriot"],
        family:"Ericaceae", spacing_cm:120, row_spacing_cm:150, days_to_harvest:365,
        companions:["Lingonberry","Cranberry","Rhododendron"],
        avoid:["Lily of the Valley","Fennel"],
        notes_growing:"Needs acidic soil pH 4.5–5.5. Needs at least 2 varieties for cross-pollination.",
    },
    {
        name:"Rhubarb", category:"Fruit",
        varieties:["Timperley Early","Victoria","Champagne","Glaskin's Perpetual"],
        family:"Polygonaceae", spacing_cm:90, row_spacing_cm:120, days_to_harvest:365,
        companions:["Columbine","Garlic"],
        avoid:["Fennel","Thistle","Dock"],
        notes_growing:"Perennial. Do not harvest in year 1. Remove flower stalks. Leaves are toxic.",
    },
    {
        name:"Gooseberry", category:"Fruit",
        varieties:["Invicta","Hinnonmäki Red","Captivator","Pax"],
        family:"Grossulariaceae", spacing_cm:120, row_spacing_cm:150, days_to_harvest:365,
        companions:["Tomato","Beans","Peas"],
        avoid:["Fennel"],
        notes_growing:"Spiny — wear gloves. Train as bush, cordon, or standard. Prone to sawfly.",
    },
    {
        name:"Currant", category:"Fruit",
        varieties:["Ben Sarek (Black)","Jonkheer van Tets (Red)","White Versailles"],
        family:"Grossulariaceae", spacing_cm:150, row_spacing_cm:180, days_to_harvest:365,
        companions:["Marigold","Nasturtium","Dill"],
        avoid:["Fennel","Weigela"],
        notes_growing:"Blackcurrants fruit on new wood — prune one-third of old growth annually.",
    },
    {
        name:"Fig", category:"Fruit",
        varieties:["Brown Turkey","Brunswick","White Marseilles","Violette de Solliès"],
        family:"Moraceae", spacing_cm:300, row_spacing_cm:300, days_to_harvest:365,
        companions:["Rue","Comfrey"],
        avoid:["Fennel"],
        notes_growing:"Restrict roots in poor soil for better fruit set. Fan-train against a south wall.",
    },
    {
        name:"Melon", category:"Fruit",
        varieties:["Blenheim Orange","Sweetheart","Emir","Ogen"],
        family:"Cucurbitaceae", spacing_cm:90, row_spacing_cm:120, days_to_harvest:90, greenhouse:true,
        companions:["Nasturtium","Marigold","Dill"],
        avoid:["Potato","Fennel"],
        notes_growing:"Needs warm conditions. Restrict to 4 fruits per plant. Greenhouse recommended in UK.",
    },
    // Flowers (companion/edible)
    {
        name:"Marigold", category:"Flower",
        varieties:["French Dwarf","African Giant","Crackerjack","Lemon Gem","Disco Orange"],
        family:"Asteraceae", spacing_cm:20, row_spacing_cm:25, days_to_harvest:60,
        companions:["Tomato","Pepper","Cucumber","Carrot","Potato","Brassicas","Rose"],
        avoid:["Fennel","Beans"],
        notes_growing:"French marigolds suppress nematodes and whitefly. Plant densely around vulnerable crops.",
    },
    {
        name:"Nasturtium", category:"Flower",
        varieties:["Jewel Mix","Alaska","Empress of India","Climbing","Black Velvet"],
        family:"Tropaeolaceae", spacing_cm:25, row_spacing_cm:30, days_to_harvest:50,
        companions:["Tomato","Cucumber","Zucchini","Brassicas","Radish","Apple"],
        avoid:["Fennel"],
        notes_growing:"Edible flowers and leaves. Trap crop for blackfly. Self-seeds freely.",
    },
    {
        name:"Sunflower", category:"Flower",
        varieties:["Dwarf Sunspot","Giant Russian","Teddy Bear","Velvet Queen","Strawberry Blonde"],
        family:"Asteraceae", spacing_cm:45, row_spacing_cm:60, days_to_harvest:80,
        companions:["Cucumber","Squash","Lettuce","Tomato"],
        avoid:["Potato","Fennel","Beans"],
        notes_growing:"Allelopathic — inhibits beans and potatoes nearby. Attracts pollinators and seed-eating birds.",
    },
    {
        name:"Calendula", category:"Flower",
        varieties:["Orange King","Lemon Cream","Pacific Beauty","Indian Prince"],
        family:"Asteraceae", spacing_cm:25, row_spacing_cm:35, days_to_harvest:50,
        companions:["Tomato","Asparagus","Carrot","Brassicas"],
        avoid:["Fennel"],
        notes_growing:"Self-seeds freely. Edible petals. Deadhead regularly to extend flowering.",
    },
    {
        name:"Sweet Pea", category:"Flower",
        varieties:["Old Spice Mix","Matucana","Cupani","Spencer Mixed","Wiltshire Ripple"],
        family:"Fabaceae", spacing_cm:15, row_spacing_cm:45, days_to_harvest:70,
        companions:["Lettuce","Spinach"],
        avoid:["Fennel","Onion"],
        notes_growing:"Sow in autumn or early spring. Pinch out growing tip for bushy plants.",
    },
    {
        name:"Cosmos", category:"Flower",
        varieties:["Purity","Sensation Mix","Dazzler","Fizzy","Cupcakes"],
        family:"Asteraceae", spacing_cm:30, row_spacing_cm:40, days_to_harvest:60,
        companions:["Tomato","Pepper","Celery"],
        avoid:["Fennel"],
        notes_growing:"Sow direct after last frost or start indoors. Self-seeds. Attracts hoverflies.",
    },
    {
        name:"Phacelia", category:"Flower",
        varieties:["Common","Lacy"],
        family:"Boraginaceae", spacing_cm:10, row_spacing_cm:20, days_to_harvest:40,
        companions:["All vegetables — green manure and pollinator magnet"],
        avoid:[],
        notes_growing:"Excellent bee plant. Can be used as green manure. Quick-growing gap filler.",
    },
];
